### ISSUE TITLE
Bug in evolve.c

### ISSUE THREAD

**Issue by NonStandardModel** [juangallostra/game-of-life#9]
Found this when making non-square worlds.

In evolve.c line 52 should be:
`if (*(state + (i + neighbours[k][0])*col + j+ neighbours[k][1]) == 1)
`
and line 58:
`*(pointer + i*col + j) = decision(cont,*(state + i*col +j));
`
Basically, to get the index into array you must multiply "row number" with "column size" (not with row size as it is now). 

Thank You!

**Comment by juangallostra** [comment]
@NonStandardModel thanks for pointing it out. Would you like to submit a PR with the fix?

**Comment by NonStandardModel** [comment]
Done.
Outstanding response :) ..less than 1h

**Comment by juangallostra** [comment]
Closed as per PR #10 

I usually keep GitHub open on a browser tab at all times 🤷‍♂️
